### ISSUE TITLE
What have you learned from creating Gaze?

### ISSUE THREAD

**Issue by sindresorhus** [shama/ama#11]
https://github.com/shama/gaze

**Comment by shama** [comment]
It taught me:
- Open source is the best
- Open source is the worst
- Turn contributors into owners asap as maintaining a popular project on your own is hard
- Everything in life is in a different state of broken
- Don't write a file watcher

Most importantly it taught me that open source should be fun. It's really stressful and impossible trying to compete with an entire world of talented developers. The perceived competition is what drove development on gaze for awhile. But then I burned out and realized it's all just not that important. So now I treat open source as a fun hobby and try to avoid getting wrapped up in the politics.

I still maintain gaze even though not very actively. Fixing other people's issues isn't very interesting but diving into the weird file system things is still a fun puzzle. Maybe something useful to someone else will come from that or maybe not. Doesn't matter as long as it was fun doing it.
