### ISSUE TITLE
What do you think about Spain?

### ISSUE THREAD

**Issue by aarroyoc** [shama/ama#16]
How do people from outside Spain thinks about Spain? and How do you think about Spain?

**Comment by shama** [comment]
I've never been to Spain but I do have family that lives in Valencia. Based on the photos I've seen and the stories they've told, visiting Spain is high on my list. It looks like a very beautiful and culturally rich country.

I need to work more on my Spanish before I go though. Most of what I've learned is based on Latin American Spanish and my little cousins tell me, "no es correcto."
