### ISSUE TITLE
What are some lessons learned from doing YouTube screencasts?

### ISSUE THREAD

**Issue by vladikoff** [shama/ama#3]

**Comment by shama** [comment]
1. Producing screencasts are not as easy as I thought they were going to be.
2. I say "umm" way more than I thought.
3. Writing a more thorough script and doing practice runs are insanely helpful.
4. My microphone is awful.
5. Trying to teach something to others helps me learn it to a very weird level of detail.
6. YouTube comments can be positive. At least I'm lucky that all of the comments I've gotten, so far, have been positive.
