### ISSUE TITLE
Do you consider Grunt done?

### ISSUE THREAD

**Issue by SBoudrias** [shama/ama#4]
If not, what are the next steps?

**Comment by shama** [comment]
That is an insanely good and difficult to answer question. Here is my best attempt:

Grunt still is and always has been @cowboy's project. Before Grunt, I didn't _really_ know JavaScript. I basically forced Ben Alman (and later @tkellen) into teaching me JS by sending a bunch of unintentionally bad PRs for them to correct and guide me. I was just excited about a project that made sense to me.

Through Grunt, I've learned a ton about JS and more importantly, have been able to interact with so many great people (such as yourself @SBoudrias).

So I don't think Grunt is done. Even though there are many (perhaps, in some ways, technically better) alternatives, Grunt currently is still a viable build tool and very much serves as a JavaScript learning gateway to many as it did me.

I can't definitively say what the next steps for Grunt are. It is ultimately up to Ben. For me, the next steps are keep experimenting through standalone modules. Hopefully the code generated from those experiments will be useful to next version of Grunt and more importantly the open source community as a whole.
